In [1]:
import pandas as pd
import numpy as np

data = np.loadtxt("C:\\Users\\schai\\Downloads\\Coding Ninjas\\PowerPlant\\Powercycle_Train.csv",delimiter = ",")

In [2]:
data

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [3]:
df = pd.DataFrame(data)

In [4]:
df = pd.read_csv("C:\\Users\\schai\\Downloads\\Coding Ninjas\\PowerPlant\\Powercycle_Train.csv")

In [5]:
df

        # T      V       AP     RH      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

In [6]:
data = df.copy()

Features consist of hourly average ambient variables 
- Temperature (T) in the range 1.81°C and 37.11°C,
- Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Exhaust Vacuum (V) in the range 25.36-81.56 cm Hg
- Net hourly electrical energy output (EP) 420.26-495.76 MW

In [7]:
df.columns = ["T","AP","RH","V","EP"]

In [8]:
df

          T     AP       RH      V      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

In [9]:
len(data)

7176

In [11]:
x_train = df.drop('EP',axis = 1)

In [12]:
x_train

          T     AP       RH      V
0      8.58  38.38  1021.03  84.37
1     21.79  58.20  1017.21  66.74
2     16.64  48.92  1011.55  78.76
3     31.38  71.32  1009.17  60.42
4      9.20  40.03  1017.05  92.46
...     ...    ...      ...    ...
7171   9.32  37.73  1022.14  79.49
7172  11.20  41.38  1021.65  61.89
7173  29.80  69.34  1009.36  64.74
7174  16.37  54.30  1017.94  63.63
7175  30.11  62.04  1010.69  47.96

[7176 rows x 4 columns]

In [13]:
y_train = df['EP']

In [19]:
y_train

0       482.26
1       446.94
2       452.56
3       433.44
4       480.38
         ...
7171    477.91
7172    476.87
7173    437.65
7174    459.97
7175    444.42
Name: EP, Length: 7176, dtype: float64

In [21]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()

x = scaler.fit_transform(x_train)

In [22]:
x

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00,
         7.58624590e-01],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01,
        -4.46921842e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01,
         3.75010552e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01,
        -5.83682640e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01,
        -6.59584883e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01,
        -1.73110573e+00]])

In [23]:
from sklearn.linear_model import SGDRegressor

In [24]:
alg = SGDRegressor()

In [25]:
alg.fit(x_train,y_train)

SGDRegressor()

In [26]:
alg.score(x_train,y_train)

-1.1211386187389732e+26

In [28]:
x_test = np.loadtxt("C:\\Users\\schai\\Downloads\\Coding Ninjas\\PowerPlant\\Powercycle_Test.csv",delimiter = ",")

In [40]:
x_test

array([[  11.95,   42.03, 1017.58,   90.89],
       [  12.07,   38.25, 1012.67,   81.66],
       [  26.91,   74.99, 1005.64,   78.98],
       ...,
       [  24.32,   66.25, 1009.09,   91.89],
       [  23.49,   42.8 , 1013.96,   65.31],
       [  21.76,   60.27, 1018.96,   85.06]])

In [57]:
y_pred = alg.predict(x_test)

In [58]:
y_pred

array([-1.71892528e+14, -1.68477336e+14, -2.48079126e+14, ...,
       -2.27076795e+14, -1.98201021e+14, -2.17094581e+14])

In [59]:
def step_gradient(points, learning_rate, m , c):
    new_m = np.zeros(points.shape[1] - 1)
    new_c = 0
    M = len(points)
    for j in range(len(m)-1):
        m_slope = 0
        c_slope = 0
        for i in range(M):
            x = points[i, j]
            y = points[i, -1]
            m_slope += (-2/M)* (y - m[j] * x - c)*x
            c_slope += (-2/M)* (y - m[j] * x - c)
            
        new_m[j] = m[j] - learning_rate * m_slope
        new_c = c - learning_rate * c_slope
    return new_m, new_c

def gd(points, learning_rate, num_iterations):
    m = np.zeros(points.shape[1] - 1)     
    c = 0     
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

def cost(points, m, c):
    total_cost = 0
    M = len(points)
    for j in range(len(m)):
        for i in range(M):
            x = points[i, j]
            y = points[i, -1]
            total_cost += (1/M)*((y - m[j]*x - c)**2)
    return total_cost

def run():
    learning_rate = 0.05
    num_iterations = 50
    m, c = gd(data, learning_rate, num_iterations)
    print("Final m :", m)
    print("Final c :", c)
    return m,c

In [ ]:
def run(x,y):
    lr = 0.01
    n = 1000
    gd(data,lr,n)

0  Cost:  870123729154.0366
1  Cost:  3.66551416061643e+18
2  Cost:  1.5441573034359701e+25
3  Cost:  6.5050131397536e+31
4  Cost:  2.7403423119011664e+38
5  Cost:  1.1544136537563505e+45
6  Cost:  4.863154789791471e+51
7  Cost:  2.0486828471333877e+58
8  Cost:  8.630408838618425e+64
9  Cost:  3.635699729019723e+71
10  Cost:  1.531597490543717e+78
11  Cost:  6.452102890444967e+84
12  Cost:  2.7180530110498782e+91
13  Cost:  1.1450239241872872e+98
14  Cost:  4.823599030744524e+104
15  Cost:  2.0320193419463567e+111
16  Cost:  8.560211119801362e+117
17  Cost:  3.606127801194178e+124
18  Cost:  1.519139836220184e+131
19  Cost:  6.399623000679351e+137
20  Cost:  2.6959450061375088e+144
21  Cost:  1.1357105684735257e+151
22  Cost:  4.784365008952566e+157
23  Cost:  2.0154913737974133e+164
24  Cost:  8.490584372744345e+170
25  Cost:  3.5767964044850063e+177
26  Cost:  1.5067835095314516e+184
27  Cost:  6.347569970013067e+190
28  Cost:  2.674016822545429e+197
29  Cost:  1.1264729654080866e+204
30  Cost:  4.7454501074805585e+210
31  Cost:  1.9990978402601022e+217
32  Cost:  8.42152395329758e+223
33  Cost:  3.5477035824688367e+230
34  Cost:  1.494527686302448e+237
35  Cost:  6.295940326474838e+243
36  Cost:  2.6522669976493968e+250
37  Cost:  1.1173104988367701e+257
38  Cost:  4.7068517306789154e+263
39  Cost:  1.982837647874968e+270
40  Cost:  8.353025255085383e+276
41  Cost:  3.5188473946351763e+283
42  Cost:  1.482371549061527e+290
43  Cost:  6.2447306263329534e+296
44  Cost:  2.630694080721524e+303
45  Cost:  inf

C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:33: RuntimeWarning: overflow encountered in double_scalars
  total_cost += (1/M)*((y - m[j]*x - c)**2)

46  Cost:  inf
47  Cost:  inf
48  Cost:  inf
49  Cost:  inf
50  Cost:  inf
51  Cost:  inf
52  Cost:  inf
53  Cost:  inf
54  Cost:  inf
55  Cost:  inf
56  Cost:  inf
57  Cost:  inf
58  Cost:  inf
59  Cost:  inf
60  Cost:  inf
61  Cost:  inf
62  Cost:  inf
63  Cost:  inf
64  Cost:  inf
65  Cost:  inf
66  Cost:  inf
67  Cost:  inf
68  Cost:  inf
69  Cost:  inf
70  Cost:  inf
71  Cost:  inf
72  Cost:  inf
73  Cost:  inf
74  Cost:  inf
75  Cost:  inf
76  Cost:  inf
77  Cost:  inf
78  Cost:  inf
79  Cost:  inf
80  Cost:  inf
81  Cost:  inf
82  Cost:  inf
83  Cost:  inf
84  Cost:  inf
85  Cost:  inf
86  Cost:  inf
87  Cost:  inf
88  Cost:  inf
89  Cost:  inf
90  Cost:  inf
91  Cost:  inf

C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:11: RuntimeWarning: overflow encountered in double_scalars
  m_slope += (-2/M)* (y - m[j] * x - c)*x

92  Cost:  inf
93  Cost:  nan

C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:14: RuntimeWarning: invalid value encountered in double_scalars
  new_m[j] = m[j] - learning_rate * m_slope
C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:15: RuntimeWarning: invalid value encountered in double_scalars
  new_c = c - learning_rate * c_slope

94  Cost:  nan
95  Cost:  nan
96  Cost:  nan
97  Cost:  nan
98  Cost:  nan
99  Cost:  nan
100  Cost:  nan
101  Cost:  nan
102  Cost:  nan
103  Cost:  nan
104  Cost:  nan
105  Cost:  nan
106  Cost:  nan
107  Cost:  nan
108  Cost:  nan
109  Cost:  nan
110  Cost:  nan
111  Cost:  nan
112  Cost:  nan
113  Cost:  nan
114  Cost:  nan
115  Cost:  nan
116  Cost:  nan
117  Cost:  nan
118  Cost:  nan
119  Cost:  nan
120  Cost:  nan
121  Cost:  nan
122  Cost:  nan
123  Cost:  nan
124  Cost:  nan
125  Cost:  nan
126  Cost:  nan
127  Cost:  nan
128  Cost:  nan
129  Cost:  nan
130  Cost:  nan
131  Cost:  nan
132  Cost:  nan
133  Cost:  nan
134  Cost:  nan
135  Cost:  nan
136  Cost:  nan
137  Cost:  nan
138  Cost:  nan
139  Cost:  nan
140  Cost:  nan
141  Cost:  nan
142  Cost:  nan
143  Cost:  nan
144  Cost:  nan
145  Cost:  nan
146  Cost:  nan
147  Cost:  nan
148  Cost:  nan
149  Cost:  nan
150  Cost:  nan
151  Cost:  nan
152  Cost:  nan
153  Cost:  nan
154  Cost:  nan
155  Cost:  nan
156  Cost:  nan
157  Cost:  nan
158  Cost:  nan
159  Cost:  nan
160  Cost:  nan
161  Cost:  nan
162  Cost:  nan
163  Cost:  nan
164  Cost:  nan
165  Cost:  nan
166  Cost:  nan
167  Cost:  nan
168  Cost:  nan
169  Cost:  nan
170  Cost:  nan
171  Cost:  nan
172  Cost:  nan
173  Cost:  nan
174  Cost:  nan
175  Cost:  nan
176  Cost:  nan
177  Cost:  nan
178  Cost:  nan
179  Cost:  nan
180  Cost:  nan
181  Cost:  nan
182  Cost:  nan
183  Cost:  nan
184  Cost:  nan
185  Cost:  nan
186  Cost:  nan
187  Cost:  nan
188  Cost:  nan
189  Cost:  nan
190  Cost:  nan
191  Cost:  nan
192  Cost:  nan
193  Cost:  nan
194  Cost:  nan
195  Cost:  nan
196  Cost:  nan
197  Cost:  nan
198  Cost:  nan
199  Cost:  nan
200  Cost:  nan
201  Cost:  nan
202  Cost:  nan
203  Cost:  nan
204  Cost:  nan
205  Cost:  nan
206  Cost:  nan
207  Cost:  nan
208  Cost:  nan
209  Cost:  nan
210  Cost:  nan
211  Cost:  nan
212  Cost:  nan
213  Cost:  nan
214  Cost:  nan
215  Cost:  nan
216  Cost:  nan
217  Cost:  nan
218  Cost:  nan
219  Cost:  nan
220  Cost:  nan
221  Cost:  nan
222  Cost:  nan
223  Cost:  nan
224  Cost:  nan
225  Cost:  nan
226  Cost:  nan
227  Cost:  nan
228  Cost:  nan
229  Cost:  nan
230  Cost:  nan
231  Cost:  nan
232  Cost:  nan
233  Cost:  nan
234  Cost:  nan
235  Cost:  nan
236  Cost:  nan
237  Cost:  nan
238  Cost:  nan
239  Cost:  nan
240  Cost:  nan
241  Cost:  nan
242  Cost:  nan
243  Cost:  nan
244  Cost:  nan
245  Cost:  nan
246  Cost:  nan
247  Cost:  nan
248  Cost:  nan
249  Cost:  nan
250  Cost:  nan
251  Cost:  nan
252  Cost:  nan
253  Cost:  nan
254  Cost:  nan
255  Cost:  nan
256  Cost:  nan
257  Cost:  nan
258  Cost:  nan
259  Cost:  nan
260  Cost:  nan
261  Cost:  nan
262  Cost:  nan
263  Cost:  nan
264  Cost:  nan
265  Cost:  nan
266  Cost:  nan
267  Cost:  nan
268  Cost:  nan
269  Cost:  nan
270  Cost:  nan
271  Cost:  nan
272  Cost:  nan
273  Cost:  nan
274  Cost:  nan
275  Cost:  nan
276  Cost:  nan
277  Cost:  nan
278  Cost:  nan
279  Cost:  nan
280  Cost:  nan
281  Cost:  nan
282  Cost:  nan
283  Cost:  nan
284  Cost:  nan
285  Cost:  nan
286  Cost:  nan
287  Cost:  nan
288  Cost:  nan
289  Cost:  nan
290  Cost:  nan
291  Cost:  nan
292  Cost:  nan
293  Cost:  nan
294  Cost:  nan
295  Cost:  nan
296  Cost:  nan
297  Cost:  nan
298  Cost:  nan
299  Cost:  nan
300  Cost:  nan
301  Cost:  nan
302  Cost:  nan
303  Cost:  nan
304  Cost:  nan
305  Cost:  nan
306  Cost:  nan
307  Cost:  nan
308  Cost:  nan
309  Cost:  nan
310  Cost:  nan
311  Cost:  nan
312  Cost:  nan
313  Cost:  nan
314  Cost:  nan
315  Cost:  nan
316  Cost:  nan
317  Cost:  nan
318  Cost:  nan
319  Cost:  nan
320  Cost:  nan
321  Cost:  nan
322  Cost:  nan
323  Cost:  nan
324  Cost:  nan
325  Cost:  nan
326  Cost:  nan
327  Cost:  nan
328  Cost:  nan
329  Cost:  nan
330  Cost:  nan
331  Cost:  nan
332  Cost:  nan
333  Cost:  nan
334  Cost:  nan
335  Cost:  nan
336  Cost:  nan
337  Cost:  nan
338  Cost:  nan
339  Cost:  nan
340  Cost:  nan
341  Cost:  nan
342  Cost:  nan
343  Cost:  nan
344  Cost:  nan
345  Cost:  nan
346  Cost:  nan
347  Cost:  nan
348  Cost:  nan
349  Cost:  nan
350  Cost:  nan
351  Cost:  nan
352  Cost:  nan
353  Cost:  nan
354  Cost:  nan
355  Cost:  nan
356  Cost:  nan
357  Cost:  nan
358  Cost:  nan
359  Cost:  nan
360  Cost:  nan
361  Cost:  nan
362  Cost:  nan
363  Cost:  nan
364  Cost:  nan
365  Cost:  nan
366  Cost:  nan
367  Cost:  nan
368  Cost:  nan
369  Cost:  nan
370  Cost:  nan
371  Cost:  nan
372  Cost:  nan
373  Cost:  nan
374  Cost:  nan
375  Cost:  nan
376  Cost:  nan
377  Cost:  nan
378  Cost:  nan
379  Cost:  nan
380  Cost:  nan
381  Cost:  nan
382  Cost:  nan
383  Cost:  nan
384  Cost:  nan
385  Cost:  nan
386  Cost:  nan
387  Cost:  nan
388  Cost:  nan
389  Cost:  nan
390  Cost:  nan
391  Cost:  nan
392  Cost:  nan
393  Cost:  nan
394  Cost:  nan
395  Cost:  nan
396  Cost:  nan
397  Cost:  nan
398  Cost:  nan
399  Cost:  nan
400  Cost:  nan
401  Cost:  nan
402  Cost:  nan
403  Cost:  nan
404  Cost:  nan
405  Cost:  nan
406  Cost:  nan
407  Cost:  nan
408  Cost:  nan
409  Cost:  nan
410  Cost:  nan
411  Cost:  nan
412  Cost:  nan
413  Cost:  nan
414  Cost:  nan
415  Cost:  nan
416  Cost:  nan
417  Cost:  nan
418  Cost:  nan
419  Cost:  nan
420  Cost:  nan
421  Cost:  nan
422  Cost:  nan
423  Cost:  nan
424  Cost:  nan
425  Cost:  nan
426  Cost:  nan
427  Cost:  nan
428  Cost:  nan
429  Cost:  nan
430  Cost:  nan
431  Cost:  nan
432  Cost:  nan
433  Cost:  nan
434  Cost:  nan
435  Cost:  nan
436  Cost:  nan
437  Cost:  nan
438  Cost:  nan
439  Cost:  nan
440  Cost:  nan
441  Cost:  nan
442  Cost:  nan
443  Cost:  nan
444  Cost:  nan
445  Cost:  nan
446  Cost:  nan
447  Cost:  nan
448  Cost:  nan
449  Cost:  nan
450  Cost:  nan
451  Cost:  nan
452  Cost:  nan
453  Cost:  nan
454  Cost:  nan
455  Cost:  nan
456  Cost:  nan
457  Cost:  nan
458  Cost:  nan
459  Cost:  nan
460  Cost:  nan
461  Cost:  nan
462  Cost:  nan
463  Cost:  nan
464  Cost:  nan
465  Cost:  nan
466  Cost:  nan
467  Cost:  nan
468  Cost:  nan
469  Cost:  nan
470  Cost:  nan
471  Cost:  nan
472  Cost:  nan
473  Cost:  nan
474  Cost:  nan
475  Cost:  nan
476  Cost:  nan
477  Cost:  nan
478  Cost:  nan
479  Cost:  nan
480  Cost:  nan
481  Cost:  nan
482  Cost:  nan
483  Cost:  nan
484  Cost:  nan
485  Cost:  nan
486  Cost:  nan
487  Cost:  nan
488  Cost:  nan
489  Cost:  nan
490  Cost:  nan
491  Cost:  nan
492  Cost:  nan
493  Cost:  nan
494  Cost:  nan
495  Cost:  nan
496  Cost:  nan
497  Cost:  nan
498  Cost:  nan
499  Cost:  nan
500  Cost:  nan
501  Cost:  nan
502  Cost:  nan
503  Cost:  nan
504  Cost:  nan
505  Cost:  nan
506  Cost:  nan
507  Cost:  nan
508  Cost:  nan
509  Cost:  nan
510  Cost:  nan
511  Cost:  nan
512  Cost:  nan
513  Cost:  nan
514  Cost:  nan
515  Cost:  nan
516  Cost:  nan
517  Cost:  nan
518  Cost:  nan
519  Cost:  nan
520  Cost:  nan
521  Cost:  nan
522  Cost:  nan
523  Cost:  nan
524  Cost:  nan
525  Cost:  nan
526  Cost:  nan
527  Cost:  nan
528  Cost:  nan
529  Cost:  nan
530  Cost:  nan
531  Cost:  nan
532  Cost:  nan
533  Cost:  nan
534  Cost:  nan
535  Cost:  nan
536  Cost:  nan
537  Cost:  nan
538  Cost:  nan
539  Cost:  nan
540  Cost:  nan
541  Cost:  nan
542  Cost:  nan
543  Cost:  nan
544  Cost:  nan
545  Cost:  nan
546  Cost:  nan
547  Cost:  nan
548  Cost:  nan
549  Cost:  nan
550  Cost:  nan
551  Cost:  nan
552  Cost:  nan
553  Cost:  nan
554  Cost:  nan
555  Cost:  nan
556  Cost:  nan
557  Cost:  nan
558  Cost:  nan
559  Cost:  nan
560  Cost:  nan
561  Cost:  nan
562  Cost:  nan
563  Cost:  nan
564  Cost:  nan
565  Cost:  nan
566  Cost:  nan
567  Cost:  nan
568  Cost:  nan
569  Cost:  nan
570  Cost:  nan
571  Cost:  nan
572  Cost:  nan
573  Cost:  nan
574  Cost:  nan
575  Cost:  nan
576  Cost:  nan
577  Cost:  nan
578  Cost:  nan
579  Cost:  nan
580  Cost:  nan
581  Cost:  nan
582  Cost:  nan
583  Cost:  nan
584  Cost:  nan
585  Cost:  nan
586  Cost:  nan
587  Cost:  nan
588  Cost:  nan
589  Cost:  nan
590  Cost:  nan
591  Cost:  nan
592  Cost:  nan
593  Cost:  nan
594  Cost:  nan
595  Cost:  nan
596  Cost:  nan
597  Cost:  nan
598  Cost:  nan
599  Cost:  nan
600  Cost:  nan
601  Cost:  nan
602  Cost:  nan
603  Cost:  nan
604  Cost:  nan
605  Cost:  nan
606  Cost:  nan
607  Cost:  nan
608  Cost:  nan

609  Cost:  nan
610  Cost:  nan
611  Cost:  nan
612  Cost:  nan
613  Cost:  nan
614  Cost:  nan
615  Cost:  nan
616  Cost:  nan
617  Cost:  nan
618  Cost:  nan
619  Cost:  nan
620  Cost:  nan
621  Cost:  nan
622  Cost:  nan
623  Cost:  nan
624  Cost:  nan
625  Cost:  nan
626  Cost:  nan
627  Cost:  nan
628  Cost:  nan
629  Cost:  nan
630  Cost:  nan
631  Cost:  nan
632  Cost:  nan
633  Cost:  nan
634  Cost:  nan
635  Cost:  nan
636  Cost:  nan
637  Cost:  nan
638  Cost:  nan
639  Cost:  nan
640  Cost:  nan
641  Cost:  nan
642  Cost:  nan
643  Cost:  nan
644  Cost:  nan
645  Cost:  nan
646  Cost:  nan
647  Cost:  nan
648  Cost:  nan
649  Cost:  nan
650  Cost:  nan
651  Cost:  nan
652  Cost:  nan
653  Cost:  nan
654  Cost:  nan
655  Cost:  nan
656  Cost:  nan
657  Cost:  nan
658  Cost:  nan
659  Cost:  nan
660  Cost:  nan
661  Cost:  nan
662  Cost:  nan
663  Cost:  nan
664  Cost:  nan
665  Cost:  nan
666  Cost:  nan
667  Cost:  nan
668  Cost:  nan
669  Cost:  nan
670  Cost:  nan
671  Cost:  nan
672  Cost:  nan
673  Cost:  nan
674  Cost:  nan
675  Cost:  nan
676  Cost:  nan
677  Cost:  nan
678  Cost:  nan
679  Cost:  nan
680  Cost:  nan
681  Cost:  nan
682  Cost:  nan
683  Cost:  nan
684  Cost:  nan
685  Cost:  nan
686  Cost:  nan
687  Cost:  nan
688  Cost:  nan
689  Cost:  nan
690  Cost:  nan
691  Cost:  nan
692  Cost:  nan
693  Cost:  nan
694  Cost:  nan
695  Cost:  nan
696  Cost:  nan
697  Cost:  nan
698  Cost:  nan
699  Cost:  nan
700  Cost:  nan
701  Cost:  nan
702  Cost:  nan
703  Cost:  nan
704  Cost:  nan
705  Cost:  nan
706  Cost:  nan
707  Cost:  nan
708  Cost:  nan
709  Cost:  nan
710  Cost:  nan
711  Cost:  nan
712  Cost:  nan
713  Cost:  nan
714  Cost:  nan
715  Cost:  nan
716  Cost:  nan
717  Cost:  nan
718  Cost:  nan
719  Cost:  nan
720  Cost:  nan
721  Cost:  nan
722  Cost:  nan
723  Cost:  nan
724  Cost:  nan
725  Cost:  nan
726  Cost:  nan
727  Cost:  nan
728  Cost:  nan
729  Cost:  nan
730  Cost:  nan
731  Cost:  nan
732  Cost:  nan
733  Cost:  nan
734  Cost:  nan
735  Cost:  nan
736  Cost:  nan
737  Cost:  nan
738  Cost:  nan
739  Cost:  nan
740  Cost:  nan
741  Cost:  nan
742  Cost:  nan
743  Cost:  nan
744  Cost:  nan
745  Cost:  nan
746  Cost:  nan
747  Cost:  nan
748  Cost:  nan
749  Cost:  nan
750  Cost:  nan
751  Cost:  nan
752  Cost:  nan
753  Cost:  nan
754  Cost:  nan
755  Cost:  nan
756  Cost:  nan
757  Cost:  nan
758  Cost:  nan
759  Cost:  nan
760  Cost:  nan
761  Cost:  nan
762  Cost:  nan
763  Cost:  nan
764  Cost:  nan
765  Cost:  nan
766  Cost:  nan
767  Cost:  nan
768  Cost:  nan
769  Cost:  nan
770  Cost:  nan
771  Cost:  nan
772  Cost:  nan
773  Cost:  nan
774  Cost:  nan
775  Cost:  nan
776  Cost:  nan
777  Cost:  nan
778  Cost:  nan
779  Cost:  nan
780  Cost:  nan
781  Cost:  nan
782  Cost:  nan
783  Cost:  nan
784  Cost:  nan
785  Cost:  nan
786  Cost:  nan
787  Cost:  nan
788  Cost:  nan
789  Cost:  nan
790  Cost:  nan
791  Cost:  nan
792  Cost:  nan
793  Cost:  nan
794  Cost:  nan
795  Cost:  nan
796  Cost:  nan
797  Cost:  nan
798  Cost:  nan
799  Cost:  nan
800  Cost:  nan
801  Cost:  nan
802  Cost:  nan
803  Cost:  nan
804  Cost:  nan
805  Cost:  nan
806  Cost:  nan
807  Cost:  nan
808  Cost:  nan
809  Cost:  nan
810  Cost:  nan
811  Cost:  nan
812  Cost:  nan
813  Cost:  nan
814  Cost:  nan
815  Cost:  nan
816  Cost:  nan
817  Cost:  nan
818  Cost:  nan
819  Cost:  nan
820  Cost:  nan
821  Cost:  nan
822  Cost:  nan
823  Cost:  nan
824  Cost:  nan
825  Cost:  nan
826  Cost:  nan
827  Cost:  nan
828  Cost:  nan
829  Cost:  nan
830  Cost:  nan
831  Cost:  nan
832  Cost:  nan
833  Cost:  nan
834  Cost:  nan
835  Cost:  nan
836  Cost:  nan
837  Cost:  nan
838  Cost:  nan
839  Cost:  nan
840  Cost:  nan
841  Cost:  nan
842  Cost:  nan
843  Cost:  nan
844  Cost:  nan
845  Cost:  nan
846  Cost:  nan
847  Cost:  nan
848  Cost:  nan
849  Cost:  nan
850  Cost:  nan
851  Cost:  nan
852  Cost:  nan
853  Cost:  nan
854  Cost:  nan
855  Cost:  nan
856  Cost:  nan
857  Cost:  nan
858  Cost:  nan
859  Cost:  nan
860  Cost:  nan
861  Cost:  nan
862  Cost:  nan
863  Cost:  nan
864  Cost:  nan
865  Cost:  nan
866  Cost:  nan
867  Cost:  nan
868  Cost:  nan
869  Cost:  nan
870  Cost:  nan
871  Cost:  nan
872  Cost:  nan
873  Cost:  nan
874  Cost:  nan
875  Cost:  nan
876  Cost:  nan
877  Cost:  nan
878  Cost:  nan
879  Cost:  nan
880  Cost:  nan
881  Cost:  nan
882  Cost:  nan
883  Cost:  nan
884  Cost:  nan
885  Cost:  nan
886  Cost:  nan
887  Cost:  nan
888  Cost:  nan
889  Cost:  nan
890  Cost:  nan
891  Cost:  nan
892  Cost:  nan
893  Cost:  nan
894  Cost:  nan
895  Cost:  nan
896  Cost:  nan
897  Cost:  nan
898  Cost:  nan
899  Cost:  nan
900  Cost:  nan
901  Cost:  nan
902  Cost:  nan
903  Cost:  nan
904  Cost:  nan
905  Cost:  nan
906  Cost:  nan
907  Cost:  nan
908  Cost:  nan
909  Cost:  nan
910  Cost:  nan
911  Cost:  nan
912  Cost:  nan
913  Cost:  nan
914  Cost:  nan
915  Cost:  nan
916  Cost:  nan
917  Cost:  nan
918  Cost:  nan
919  Cost:  nan
920  Cost:  nan
921  Cost:  nan
922  Cost:  nan
923  Cost:  nan
924  Cost:  nan
925  Cost:  nan
926  Cost:  nan
927  Cost:  nan
928  Cost:  nan
929  Cost:  nan
930  Cost:  nan
931  Cost:  nan
932  Cost:  nan
933  Cost:  nan
934  Cost:  nan
935  Cost:  nan
936  Cost:  nan
937  Cost:  nan
938  Cost:  nan
939  Cost:  nan
940  Cost:  nan
941  Cost:  nan
942  Cost:  nan
943  Cost:  nan
944  Cost:  nan
945  Cost:  nan
946  Cost:  nan
947  Cost:  nan
948  Cost:  nan
949  Cost:  nan
950  Cost:  nan
951  Cost:  nan
952  Cost:  nan
953  Cost:  nan
954  Cost:  nan
955  Cost:  nan
956  Cost:  nan
957  Cost:  nan
958  Cost:  nan
959  Cost:  nan
960  Cost:  nan
961  Cost:  nan
962  Cost:  nan
963  Cost:  nan
964  Cost:  nan
965  Cost:  nan
966  Cost:  nan
967  Cost:  nan
968  Cost:  nan
969  Cost:  nan
970  Cost:  nan
971  Cost:  nan
972  Cost:  nan
973  Cost:  nan
974  Cost:  nan
975  Cost:  nan
976  Cost:  nan
977  Cost:  nan
978  Cost:  nan
979  Cost:  nan
980  Cost:  nan
981  Cost:  nan
982  Cost:  nan
983  Cost:  nan
984  Cost:  nan
985  Cost:  nan
986  Cost:  nan
987  Cost:  nan
988  Cost:  nan
989  Cost:  nan
990  Cost:  nan
991  Cost:  nan
992  Cost:  nan
993  Cost:  nan
994  Cost:  nan
995  Cost:  nan
996  Cost:  nan
997  Cost:  nan
998  Cost:  nan
999  Cost:  nan

TypeError: cannot unpack non-iterable NoneType object

In [46]:
y_pred.shape

(2392,)

In [47]:
pred_file_path = "C:\\Users\\schai\\Downloads\\PowerCycle_Output.csv"
np.savetxt(pred_file_path ,y_pred, fmt='%.5f')