In [1]:
import pandas as pd

In [6]:
marks = pd.read_csv("C:\\Users\\schai\\Downloads\\DAA-MINOR-1-Marks-_1_.csv")

In [8]:
marks

,SERIAL NO,Admission No,Bracnch,Name of the Student,Minor 1 Marks,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 998,Unnamed: 999,Unnamed: 1000,Unnamed: 1001,Unnamed: 1002,Unnamed: 1003,Unnamed: 1004,Unnamed: 1005,Unnamed: 1006,Unnamed: 1007
0,1,se20ucse001,CSE,A Teja Anvesh Yadav,46.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,se20ucse002,CSE,Aaryan Nair,14.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,se20ucse003,CSE,Aashish Reddy T,14.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,se20ucse004,CSE,Aayushi Singh,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,se20ucse005,CSE,Abhi Rohan,15.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,528,se20ucam040,CM,Venkat Nayan Reddy Mallagari,16.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,529,se20ucam041,CM,Gauransh Khurana,45.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,530,se20ucam042,CM,Bhuvan Joshi,41.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,531,se20ucam044,CM,Harshit Malik,32.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,532,se20ucam045,CM,Ambati Sabdha,36.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
count = 0
for i in marks["Minor 1 Marks"]:
    if i>50:
        count = count+1
        print(i)
print(count)

56.0
54.0
52.0
55.0
51.0
55.0
51.0
52.0
8