## Gradient Descent for n variables

In [ ]:
import numpy as np
import pandas as pd

Boston = np.loadtxt("C:\\Users\\schai\\Downloads\\0000000000002417_training_boston_x_y_train.csv",delimiter = ",")

In [3]:
type(Boston)

numpy.ndarray

In [4]:
df = pd.DataFrame(Boston)

In [5]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007,22.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,-0.204929,-0.487722,1.231945,3.668398,0.434551,2.161728,1.053485,-0.833960,-0.523001,-0.031105,-1.736418,0.361122,-1.504494,50.0
375,0.231398,-0.487722,1.015999,-0.272599,1.367490,0.215644,0.687212,-0.703186,1.661245,1.530926,0.806576,-2.812183,0.499991,14.3
376,-0.408311,-0.487722,0.247057,-0.272599,-1.016689,-0.206055,-0.809889,0.140451,-0.523001,-0.060801,0.113032,0.332066,-0.334043,20.8
377,-0.410620,-0.487722,-1.152214,-0.272599,-0.818007,0.068904,-1.826921,0.674814,-0.637962,0.129256,-0.719220,0.203235,-0.744752,22.6
378,0.342909,-0.487722,1.015999,3.668398,0.659147,1.041946,1.028593,-1.232462,1.661245,1.530926,0.806576,0.387875,-1.358713,50.0

In [9]:
x_train = df.drop(13,axis = 1)

In [10]:
x_train

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007
...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,-0.204929,-0.487722,1.231945,3.668398,0.434551,2.161728,1.053485,-0.833960,-0.523001,-0.031105,-1.736418,0.361122,-1.504494
375,0.231398,-0.487722,1.015999,-0.272599,1.367490,0.215644,0.687212,-0.703186,1.661245,1.530926,0.806576,-2.812183,0.499991
376,-0.408311,-0.487722,0.247057,-0.272599,-1.016689,-0.206055,-0.809889,0.140451,-0.523001,-0.060801,0.113032,0.332066,-0.334043
377,-0.410620,-0.487722,-1.152214,-0.272599,-0.818007,0.068904,-1.826921,0.674814,-0.637962,0.129256,-0.719220,0.203235,-0.744752
378,0.342909,-0.487722,1.015999,3.668398,0.659147,1.041946,1.028593,-1.232462,1.661245,1.530926,0.806576,0.387875,-1.358713

In [11]:
y_train = df[13]

In [12]:
y_train

0      37.9
1      21.4
2      12.7
3      19.9
4      22.5
       ...
374    50.0
375    14.3
376    20.8
377    22.6
378    50.0
Name: 13, Length: 379, dtype: float64

In [14]:
x_train.shape

(379, 13)

In [15]:
y_train.shape

(379,)

In [ ]:


## Gradient Descent Function 

def step_grad(data,lr,f,m):
    

def GradientDescent(data, lr, f, m,n):
    for i in range(n):
        m = step_grad(data,lr,f,m)
    


def run():
    data = df
    lr = 0.001
    features = 14
    n = 1000
    m = [0]*13 + [1]
    GradientDescent(data,lr,features,m,n)